[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

# API function redirect
[[redirects]]
  from = "/api/subscribe"
  to = "/.netlify/functions/subscribe"
  status = 200

# SPA fallback: route all other requests to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
