name: E2E

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  playwright:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [chromium, firefox, webkit]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        env:
          CI: true
          UNSKIP_RECENTLY_VIEWED: "1"
        run: npx playwright test --project=${{ matrix.browser }} --reporter=line

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report-${{ matrix.browser }}
          path: playwright-report
          if-no-files-found: ignore